extends Node


signal close_guidebook

signal new_game

#Квесты Экг
signal _on_ekg_quest_button_1_pressed
signal _on_ekg_quest_button_2_pressed
signal _on_ekg_quest_button_3_pressed
signal _on_ekg_quest_button_4_pressed

signal _on_uzi_quest_button_1_pressed
signal _on_uzi_quest_button_2_pressed
signal _on_uzi_quest_button_3_pressed
signal _on_uzi_quest_button_4_pressed

signal _on_analiz_quest_button_1_pressed
signal _on_analiz_quest_button_2_pressed
signal _on_analiz_quest_button_3_pressed
signal _on_analiz_quest_button_4_pressed

signal _on_furniture_quest_button_1_pressed
signal _on_furniture_quest_button_2_pressed
signal _on_furniture_quest_button_3_pressed
signal _on_furniture_quest_button_4_pressed


signal win
signal lose
	

